apiVersion: v1
kind: Service
metadata:
  name: weatherapi-service
  namespace: apiservices
spec:
  selector:
    app: weatherapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
  namespace: apiservices
spec:
  selector:
    matchLabels:
      app: weatherapi
  replicas: 3 # Change this to the desired number of replicas
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
        - name: weatherapi
          image: acrhdhciintegration.azurecr.io/weatherapi:v1.2.1
          ports:
            - containerPort: 80 # Change this to the desired port number
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: acrhdhciintegration-secret
